version: '3.8'

services:
  ros2_jazzy:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2_jazzy_dev
    container_name: ros2_jazzy_container
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      # Forward X11 graphics to the host system
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Mount the code from the local folder into the container
      - ./:/workspace
      # Mount the Gazebo models from the local folder into the container
      - ./px4_models/x500_lidar:/PX4-Autopilot/Tools/simulation/gz/models/x500_lidar
    devices:
      # Allow the container to access the GPU for rendering
      - /dev/dri:/dev/dri
    working_dir: /workspace
    stdin_open: true
    tty: true
